Fix: Upgrade SQLAlchemy to 2.0.36 for Python 3.13 compatibility
SQLAlchemy 2.0.23 fails on Python 3.13 with:
AssertionError: Class SQLCoreOperations has additional attributes
{'__firstlineno__', '__static_attributes__'}

Python 3.13 added new dunder attributes that older SQLAlchemy versions
don't handle. Upgrading to 2.0.36 resolves this issue.